apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        nodegroup: backend  # or frontend
      containers:
      - name: web
        image: krishmint/openflights:v6
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:postgres@postgres:5432/openflights_development"
        volumeMounts:
        - name: packs
          mountPath: /app/public/packs
        command: ["bash", "-c"]
        args: ["rm -f tmp/pids/server.pid && bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"]
      volumes:
      - name: packs
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: web


# apiVersion: v1    
# kind: Service
# metadata:
#   name: web
# spec:
#   type: NodePort
#   selector:
#     app: web
#   ports:
#     - port: 3000          # Cluster-internal port (ClusterIP)
#       targetPort: 3000    # Port on the container
#       nodePort: 31300     # Optional: fixed NodePort (or leave blank to auto-assign)
